[client]
name = "pve"
remote_addr = "localhost:2333"
default_token = "123"

[client.services.foo1]
local_addr = "127.0.0.1:80"

[servers.hk]
remote_addr = "localhost:2333"
default_token = "123"

[servers.cn]
remote_addr = "localhost:2444"
default_token = "123"


