[package]
name = "rathole"
version = "0.1.0"
edition = "2021"
authors = ["Yujia Qiao <code@rapiz.me>"]
description = "A reverse proxy for NAT traversal"
license-file = "LICENSE"
repository = "https://github.com/rapiz1/rathole"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[profile.bench]
debug = 1

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = { version = "1"}
clap = { version = "3.0.0-rc.7", features = ["derive"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0"
ring = "0.16"
bincode = "1"
lazy_static = "1.4.0"
hex = "0.4"
rand = "0.8.0"
backoff = { version="0.3.0", features=["tokio"] }
tracing = "0.1"
tracing-subscriber = "0.2"
socket2 = "0.4"
fdlimit = "0.2.1"
tokio-native-tls = "0.3.0"
async-trait = "0.1.52"
