[client]
remote_addr = "localhost:2333"
default_token = "123"

[client.transport]
type = "quic"
[client.transport.quic]
trusted_root = "example/quic/test_ca.pem"
hostname = "testserver"

[client.services.foo1]
local_addr = "127.0.0.1:80"
