[server]
bind_addr = "0.0.0.0:2333"
default_token = "123"

[server.transport]
type = "quic"
[server.transport.quic]
pkcs12 = "example/quic/test_server.pfx"
pkcs12_password = "1234"

[server.services.foo1]
bind_addr = "0.0.0.0:5202"
